### ISSUE TITLE
type '_WebSocketProtocolTransformer' is not a subtype of type 'StreamTransformer<Uint8List, dynamic>' of 'streamTransformer' after upgrading from Dart SDK 2.4.1 to 2.5.0

### ISSUE THREAD

**Issue by keertip** [dart-lang/webdev#660]
@halverneus commented on [Wed Sep 11 2019](https://github.com/dart-lang/sdk/issues/38328)

What I'm seeing when running "webdev build" with webdev version 2.3.0:

[SEVERE] ERROR - 2019-09-11 11:27:31.606401
[SEVERE] Asynchronous error
[SEVERE] type '_WebSocketProtocolTransformer' is not a subtype of type 'StreamTransformer<Uint8List, dynamic>' of 'streamTransformer'
[SEVERE] dart:async                                                       Stream.transform
[SEVERE] package:web_socket_channel/src/copy/web_socket_impl.dart 728:28  new WebSocketImpl.fromSocket
[SEVERE] package:web_socket_channel/src/channel.dart 94:26                new WebSocketChannel
[SEVERE] package:shelf_web_socket/src/web_socket_handler.dart 77:25       WebSocketHandler.handle.<fn>
[SEVERE] 

I get the same error if I update all my dependencies to the latest:
  build_runner: ^1.6.9
  build_web_compilers: ^2.3.0
  sass_builder: ^2.1.3

The problem goes away when I downgrade back to 2.4.1.

**Comment by keertip** [comment]
@grouma, can you triage? Thanks!

**Comment by grouma** [comment]
The underlying issue has been fixed. You'll want to do a `pub upgrade`. You'll likely also need to `pub run build_runner clean`.

**Comment by halverneus** [comment]
All good! Thanks!

**Comment by JeromePuttemans** [comment]
Hello, 
I have the same problem after migrating from 2.1.0 to 2.6.1 even after `pub upgrade` and `pub run build_runner clean`.

Here is my pubspec configuration :

```
environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  resource: ^2.1.6
  vector_math: ^2.0.8
  logging: ^0.11.3+2
  stack_trace: ^1.9.3
  reflectable: ^2.2.0

dev_dependencies:
  build_runner: ^1.7.2
  build_web_compilers: ^2.7.1
  build_test: ^0.10.10
  test: ^1.9.4
```
```

[SEVERE] ERROR - 2019-12-03 00:43:03.855360
[SEVERE] Asynchronous error
[SEVERE] type '_WebSocketProtocolTransformer' is not a subtype of type 'StreamTransformer<Uint8List, dynamic>' of 'streamTransformer'
[SEVERE] dart:async                                                       Stream.transform
[SEVERE] package:web_socket_channel/src/copy/web_socket_impl.dart 728:28  new WebSocketImpl.fromSocket
[SEVERE] package:web_socket_channel/src/channel.dart 94:26                new WebSocketChannel
[SEVERE] package:shelf_web_socket/src/web_socket_handler.dart 77:25       WebSocketHandler.handle.<fn>
```



 have you another suggestion ?

**Comment by grouma** [comment]
Try `rm -rf .dart_tool` in your workspace.

**Comment by JeromePuttemans** [comment]
Hello, thank u but removing the .dart_tool folder didn't fix the problem.

As it seems to be a casting error and after some invetigation in the code  so I tried to replace the type List<int> by Uint8List in the _WebSocketProtocolTransformer class and this fix the problem correctly.

`type '_WebSocketProtocolTransformer' is not a subtype of type 'StreamTransformer<Uint8List, dynamic>' of 'streamTransformer'`
![image](https://user-images.githubusercontent.com/33145301/70059116-7bacc800-15e0-11ea-9bcd-521258a995a3.png)

Hope this will help to fix the problem.

May this issue be re-opened ?

**Comment by jakemac53** [comment]
You need to upgrade your dependencies (with `pub upgrade` or `flutter pub upgrade`)

**Comment by JeromePuttemans** [comment]
I did that again : No dependencies changed.

**Comment by jakemac53** [comment]
You will have to figure out why you aren't getting the latest versions then - specifically you need [web_socket_channel 1.0.14](https://pub.dev/packages/web_socket_channel#1014) or greater.

You can add that constraint to your pubspec to get a better message about what other dependencies are holding you back from getting that.

**Comment by JeromePuttemans** [comment]
indeed, I removed the pubspeck.lock, re-run and I get this

```
web_socket_channel:
    dependency: transitive
    description:
      name: web_socket_channel
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
```

Thanks
